version: '3.7'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=trello
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../volumes/postgres/:/var/lib/postgresql/data/
      - ./initdb/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ../volumes/pgadmin/:/var/lib/pgadmin/
    ports:
      - 9999:80
