version: '3.7'

services:
  traefik:
    image: traefik:2.5
    ports:
      - 8880:8080
      - 8088:80
    volumes:
      - ./:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik: 
    external: true